### Login
POST http://localhost:5005/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testing123"
}

> {% client.global.set("auth_token", response.body.token); %}

### GetRandomDog
GET http://localhost:5005/api/matches/find
Authorization: Bearer {{auth_token}}

> {% client.global.set("random_dog", response.body._id); %}

### LikeRandomDog
POST http://localhost:5005/api/matches/like
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "dog_id": "{{random_dog}}",
  "status": "liked"
}

